### ISSUE TITLE
BUG:Fix the Website

### ISSUE THREAD

**Issue by PriyaGhosal** [PriyaGhosal/BuddyTrail#347] opened 2024-10-09 05:24 UTC
### What happened?

**Remove** the code and make it look like **before** as overlapping is done 

 BEFORE:
![image](https://github.com/user-attachments/assets/25069db6-7371-4a2b-a031-d365edf37d84)
![image](https://github.com/user-attachments/assets/3c6b8e47-4375-4e85-a399-8b456d9d7789)
 
NOW :
![image](https://github.com/user-attachments/assets/e144897d-6344-429e-999f-440c6367322f)
![image](https://github.com/user-attachments/assets/20172a61-06c3-4bb0-b0b9-faf8b8d1d958)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PiyushhBansal** [comment] 2024-10-09 06:10
assign this issue to me please

**Comment by PriyaGhosal** [comment] 2024-10-09 07:46
@PiyushhBansal Assigned
Please change footer also

**Comment by PriyaGhosal** [comment] 2024-10-09 12:00
@PiyushhBansal What's the update ... Are you working on it ??

**Comment by PiyushhBansal** [comment] 2024-10-09 12:02
Yess maam i am working on it will do it by tonight

**Comment by souvikpramanikgit** [comment] 2024-10-09 19:44
Assign this issue to me

**Comment by souvikpramanikgit** [comment] 2024-10-09 19:45
I will do it

**Comment by PiyushhBansal** [comment] 2024-10-09 19:47
i have already done this issue and pushed also .

**Comment by souvikpramanikgit** [comment] 2024-10-09 21:26
Your issue is not merged @PiyushhBansal .The issue is currently showing closed.

**Comment by Codersweta7** [comment] 2024-10-20 06:10
@PriyaGhosal 
Assign this issue to me , I will make user appealing page .

**Closed** 2024-10-28 09:44 UTC
Labels: bug, help wanted, hacktoberfest-accepted, gssoc-ext, level2
